#!/bin/sh

# Create display device if not present
if ! [ -e /dev/dbox/oled0 ] ; then
	mkdir -p /dev/dbox
	/bin/mknod /dev/dbox/oled0 c 147 0
fi

# Create hdmi cec device
if ! [ -e /dev/hdmi_cec ] ; then
        /bin/mknod /dev/hdmi_cec c 149 0
fi

# set booster start frequenz
if [ "$(grep config.plugins.booster.startfrequenz= /etc/enigma2/settings | sed 's/config.plugins.booster.startfrequenz=//g')" != "" ]; then
	echo  $(grep config.plugins.booster.startfrequenz= /etc/enigma2/settings | sed 's/config.plugins.booster.startfrequenz=//g') > /proc/cpu_frequ/pll0_ndiv_mdiv
fi